### ISSUE TITLE
Contribution checklist doesn't specify features

### ISSUE THREAD

**Issue by wildeyes** [process-bot/contribution-checklist#9]
The checklist talks about bugs and questions, but does not refer to feature requests / discussions, as often happens on github issues. What should be the formal way of introducing these?

**Comment by evancz** [comment]
I recommend watching [this talk](https://www.youtube.com/watch?v=DSjbTC-hvqQ) to learn about how Elm does things different on these topics than other projects.

Discussions tend to happen on mailing lists, slack, video calls, and in person. Furthermore, tracking feature requests on github is a weird way to track feature requests in my opinion. I think it is much more valuable to log problems that people run into. That way solutions can be evaluated on a variety of concrete cases.
